WIP: 712 derive auxiliary for se
ONSdigital/monthly-business-survey-results pull request #139
Opened 2024-12-18 18:30 UTC by robertswh

# Pull Request Title

Derive auxiliary variable for the selective editing output

# Summary

Derive the required auxiliary variables for Q49 for the selective editing output for SPP

# Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe):

# Checklists

This pull request meets the following requirements:

## Creator Checklist

- [ ] Installable with all dependencies recorded
- [ ] Runs without error
- [ ] Follows PEP8 and project-specific conventions
- [ ] Appropriate use of comments, for example, no descriptive comments
- [ ] Functions documented using Numpy style docstrings
- [ ] Assumptions and decisions log considered and updated if appropriate
- [ ] Unit tests have been updated to cover essential functionality for a reasonable range of inputs and conditions
- [ ] Other forms of testing such as end-to-end and user-interface testing have been considered and updated as required

If you feel some of these conditions do not apply for this pull request, please
add a comment to explain why.

## Reviewer Checklist

- [ ] Test suite passes (locally as a minimum)
- [ ] Peer reviewed with review recorded

# Additional Information

Please provide any additional information or context that would help the reviewer understand the changes in this pull request.

# Related Issues

Link any related issues or pull requests here.

2024-12-18 18:33 UTC, robertswh commented on mbs_results/outputs/selective_editing.py
> +        .drop_duplicates()
maybe we should look for duplicates in imputation_class and question_no as a quick check?

2024-12-19 14:54 UTC, robertswh commented on mbs_results/outputs/selective_editing.py
> +    current_df = dataframe[(dataframe[period] == period_selected)]
convert frozen turnover to pounds monthly

2024-12-19 14:59 UTC, robertswh commented on mbs_results/outputs/selective_editing_contributer_output.py
> +            "construction_link",
get rid of this

2024-12-22 13:35 UTC, robertswh commented on mbs_results/outputs/selective_editing_question_output.py
> +    question_output = pd.merge(standardising_factor, auxiliary_value, on=["reference", "imputation_class", "questioncode"], how="left")
doesn't make sense to merge on reference and imputation_class, one or the other

2025-01-14 16:53 UTC, Jday7879 approved these changes
Code looks good to me, Nice work :) I've made a couple of small comments and one nitpick about using .loc to remove the double indexing, not sure which method is actually better though

2025-01-14 16:53 UTC, Jday7879 commented on mbs_results/outputs/selective_editing.py
> +    # TODO: This has already been combined somewhere updstream
Is this function still needed in the pipeline. From what I can see its only called in unit tests

2025-01-14 16:53 UTC, Jday7879 commented on mbs_results/outputs/selective_editing.py
> +        there is one contruction link per imputation_class and period
```suggestion
        there is one construction link per imputation_class and period
```

2025-01-14 16:53 UTC, Jday7879 commented on mbs_results/outputs/selective_editing.py
> +    prev_const_link = (
Nitpick: Could maybe refactor to use .loc not sure which one is better in the long term?

```
dataframe.loc[
    (dataframe[period] == previous_period) & (dataframe[question_no] == 49),
    [imputation_class, construction_link, question_no]
]
```

2025-01-14 16:53 UTC, Jday7879 commented on mbs_results/outputs/selective_editing.py
> +        .drop_duplicates()
Not sure if we have a generic validation, but something similar is done when producing SE outputs

2025-01-16 11:17 UTC, Jday7879 requested changes
Changing PR from approved to request changes to avoid it being merged early following todays stand-up

2025-01-24 08:53 UTC, Jday7879 approved these changes
Looks good to me, merging :)

2025-01-24 08:53 UTC, merged