551 non response
ONSdigital/monthly-business-survey-results pull request #88
Opened 2024-09-20 13:43 UTC by KateyMatthews

# Summary

Add your summary here - keep it brief, to the point, and in plain English.

# Checklists

This pull request meets the following requirements:

- [ ] installable with all dependencies recorded
- [ ] runs without error
- [ ] follows PEP8 and project specific conventions
- [ ] appropriate use of comments, for example no descriptive comments
- [ ] functions documented using Numpy style docstings
- [ ] assumptions and decisions log considered and updated if appropriate
- [ ] unit tests have been updated to cover essential functionality for a reasonable range of inputs and conditions
- [ ] other forms of testing such as end-to-end and user-interface testing have been considered and updated as required
- [ ] tests suite passes (locally as a minimum)
- [ ] peer reviewed with review recorded

If you feel some of these conditions do not apply for this pull request, please
add a comment to explain why.

2024-09-24 10:41 UTC, Jday7879 requested changes
Code looks good to me, a couple of comments and one issue when explaning unit tests to include forms not given in mapper. Also would it be worth while to update config to include all possible mappings from form and question numbers?

2024-09-27 12:14 UTC, KateyMatthews commented on mbs_results/create_missing_questions.py
> +    return responses_reindexed.reset_index()
Slight code change to compare dataframes instead of indices.

2024-09-27 12:15 UTC, KateyMatthews commented on tests/test_create_missing_questions.py
> +        actual_output = create_missing_questions(
Added a line of code to remove empty lists before exploding. Also added test case to the data.

2024-09-30 08:12 UTC, Jday7879 approved these changes
Nice work dealing with this strange behaviour. I can see that you have added that case to the unit test data and passes as expected. Happy to be merged now :)

2024-09-30 09:19 UTC, merged